language: objective-c
osx_image: xcode10

before_install:
  - bundle install
  - brew update
  - brew outdated xctool || brew upgrade xctool

addons:
  sonarcloud:
    organization: teknasyon
    token:
      secure: dcad13541bf45043e9943d42958d6fdd028af74e

script:
  - set -o pipefail
  - xcodebuild -project PersistenceKit.xcodeproj/ -scheme PersistenceKit -derivedDataPath Build/ -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-json-formatter`
  - bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/*_Test/*.xccovarchive/ > sonarqube-generic-coverage.xml 
  - sonar-scanner
